name: Fullstack Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./UnitTesting/backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt
      - run: pip install pytest

      - run: pytest

  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./UnitTesting/frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm test